"""add_time_created_and_time_first_project_created_to_users

Revision ID: 0ad98d4b6b2b
Revises: 39c9d2e21318
Create Date: 2025-08-07 16:19:18.092562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ad98d4b6b2b'
down_revision: Union[str, Sequence[str], None] = '39c9d2e21318'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns as nullable first
    op.add_column('users', sa.Column('time_created', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('time_first_project_created', sa.DateTime(), nullable=True))
    
    # Update existing records with a default value
    op.execute("UPDATE users SET time_created = NOW() WHERE time_created IS NULL")
    
    # Make time_created NOT NULL
    op.alter_column('users', 'time_created', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'time_first_project_created')
    op.drop_column('users', 'time_created')
    # ### end Alembic commands ###
