"""Add notes field to source_materials

Revision ID: 231055637626
Revises: 3f29a4b4ac3f
Create Date: 2025-07-06 19:54:02.635414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '231055637626'
down_revision: Union[str, Sequence[str], None] = '3f29a4b4ac3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_materials', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source_materials', 'notes')
    # ### end Alembic commands ###
