"""Add source_handle and target_handle to card_links

Revision ID: 38b4a7e409d5
Revises: 87ea90f05177
Create Date: 2025-07-13 15:01:09.989721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38b4a7e409d5'
down_revision: Union[str, Sequence[str], None] = '87ea90f05177'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_card_id', sa.Integer(), nullable=True),
    sa.Column('target_card_id', sa.Integer(), nullable=True),
    sa.Column('source_handle', sa.String(), nullable=True),
    sa.Column('target_handle', sa.String(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['source_card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['target_card_id'], ['cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_links_id'), 'card_links', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_card_links_id'), table_name='card_links')
    op.drop_table('card_links')
    # ### end Alembic commands ###
