"""add_content_formatted_to_source_materials

Revision ID: 39c9d2e21318
Revises: 4fddbcc4c56f
Create Date: 2025-08-07 15:23:55.152057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39c9d2e21318'
down_revision: Union[str, Sequence[str], None] = '4fddbcc4c56f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_materials', sa.Column('content_formatted', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source_materials', 'content_formatted')
    # ### end Alembic commands ###
