"""add_formatted_text_columns_to_all_card_types

Revision ID: 4fddbcc4c56f
Revises: 5518ab406807
Create Date: 2025-08-07 13:35:05.354429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fddbcc4c56f'
down_revision: Union[str, Sequence[str], None] = '5518ab406807'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claims', sa.Column('claim_text_formatted', sa.String(), nullable=True))
    op.add_column('insights', sa.Column('insight_text_formatted', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('question_text_formatted', sa.String(), nullable=True))
    op.add_column('thoughts', sa.Column('thought_text_formatted', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('thoughts', 'thought_text_formatted')
    op.drop_column('questions', 'question_text_formatted')
    op.drop_column('insights', 'insight_text_formatted')
    op.drop_column('claims', 'claim_text_formatted')
    # ### end Alembic commands ###
