"""add_summary_formatted_to_source_materials

Revision ID: 5518ab406807
Revises: 66f0a6d48492
Create Date: 2025-08-07 12:20:48.085594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5518ab406807'
down_revision: Union[str, Sequence[str], None] = '66f0a6d48492'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_materials', sa.Column('summary_formatted', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source_materials', 'summary_formatted')
    # ### end Alembic commands ###
