"""Change tags fields to ARRAY type for all card types

Revision ID: 665fdf05663b
Revises: b18dfeebf39f
Create Date: 2025-07-17 10:31:36.474471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '665fdf05663b'
down_revision: Union[str, Sequence[str], None] = 'b18dfeebf39f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
