"""add_files_to_questions_and_create_insights_thoughts_tables

Revision ID: 87ea90f05177
Revises: c795ab00d5c1
Create Date: 2025-07-10 08:29:58.319741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87ea90f05177'
down_revision: Union[str, Sequence[str], None] = 'c795ab00d5c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('insight_text', sa.String(), nullable=False),
    sa.Column('sources_linked', sa.String(), nullable=True),
    sa.Column('files', sa.String(), nullable=True),
    sa.Column('insight_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insights_id'), 'insights', ['id'], unique=False)
    op.create_table('thoughts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('thought_text', sa.String(), nullable=False),
    sa.Column('files', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thoughts_id'), 'thoughts', ['id'], unique=False)
    op.add_column('questions', sa.Column('files', sa.String(), nullable=True))
    op.add_column('insights', sa.Column('insight_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'files')
    op.drop_index(op.f('ix_thoughts_id'), table_name='thoughts')
    op.drop_table('thoughts')
    op.drop_index(op.f('ix_insights_id'), table_name='insights')
    op.drop_table('insights')
    op.drop_column('insights', 'insight_type')
    # ### end Alembic commands ###
