"""add password reset code table

Revision ID: 8e95d946c539
Revises: 4e5fce9f6903
Create Date: 2025-07-08 21:52:57.043480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e95d946c539'
down_revision: Union[str, Sequence[str], None] = '4e5fce9f6903'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_codes_id'), 'password_reset_codes', ['id'], unique=False)
    op.drop_constraint(op.f('card_links_project_id_fkey'), 'card_links', type_='foreignkey')
    op.create_foreign_key(None, 'card_links', 'projects', ['project_id'], ['id'])
    op.drop_constraint(op.f('cards_project_id_fkey'), 'cards', type_='foreignkey')
    op.create_foreign_key(None, 'cards', 'projects', ['project_id'], ['id'])
    op.drop_constraint(op.f('citations_project_id_fkey'), 'citations', type_='foreignkey')
    op.create_foreign_key(None, 'citations', 'projects', ['project_id'], ['id'])
    op.drop_constraint(op.f('source_materials_project_id_fkey'), 'source_materials', type_='foreignkey')
    op.create_foreign_key(None, 'source_materials', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'source_materials', type_='foreignkey')
    op.create_foreign_key(op.f('source_materials_project_id_fkey'), 'source_materials', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'citations', type_='foreignkey')
    op.create_foreign_key(op.f('citations_project_id_fkey'), 'citations', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.create_foreign_key(op.f('cards_project_id_fkey'), 'cards', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'card_links', type_='foreignkey')
    op.create_foreign_key(op.f('card_links_project_id_fkey'), 'card_links', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_password_reset_codes_id'), table_name='password_reset_codes')
    op.drop_table('password_reset_codes')
    # ### end Alembic commands ###
