"""add_assignment_filename_to_projects

Revision ID: 999082ad6f13
Revises: fcb1fd711495
Create Date: 2025-07-29 22:20:57.139904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '999082ad6f13'
down_revision: Union[str, Sequence[str], None] = 'fcb1fd711495'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('assignment_filename', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'assignment_filename')
    # ### end Alembic commands ###
