"""add_tags_to_all_card_types

Revision ID: b18dfeebf39f
Revises: d4e5045a246f
Create Date: 2025-07-16 20:43:37.434983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b18dfeebf39f'
down_revision: Union[str, Sequence[str], None] = 'd4e5045a246f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claims', sa.Column('tags', sa.String(), nullable=True))
    op.add_column('insights', sa.Column('tags', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('tags', sa.String(), nullable=True))
    op.add_column('thoughts', sa.Column('tags', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('thoughts', 'tags')
    op.drop_column('questions', 'tags')
    op.drop_column('insights', 'tags')
    op.drop_column('claims', 'tags')
    # ### end Alembic commands ###
