"""add_file_filenames_to_all_card_types

Revision ID: dd63c8379965
Revises: 999082ad6f13
Create Date: 2025-07-31 12:58:35.893966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd63c8379965'
down_revision: Union[str, Sequence[str], None] = '999082ad6f13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claims', sa.Column('file_filenames', sa.String(), nullable=True))
    op.add_column('insights', sa.Column('file_filenames', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('file_filenames', sa.String(), nullable=True))
    op.add_column('source_materials', sa.Column('file_filenames', sa.String(), nullable=True))
    op.add_column('thoughts', sa.Column('file_filenames', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('thoughts', 'file_filenames')
    op.drop_column('source_materials', 'file_filenames')
    op.drop_column('questions', 'file_filenames')
    op.drop_column('insights', 'file_filenames')
    op.drop_column('claims', 'file_filenames')
    # ### end Alembic commands ###
