"""add_project_fields

Revision ID: fcb1fd711495
Revises: 6e74739aee5b
Create Date: 2025-07-29 21:07:22.280804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcb1fd711495'
down_revision: Union[str, Sequence[str], None] = '6e74739aee5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('class_subject', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('paper_type', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('due_date', sa.Date(), nullable=True))
    op.add_column('projects', sa.Column('last_edited_date', sa.DateTime(), nullable=True))
    op.add_column('projects', sa.Column('status', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('assignment_file', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'assignment_file')
    op.drop_column('projects', 'status')
    op.drop_column('projects', 'last_edited_date')
    op.drop_column('projects', 'due_date')
    op.drop_column('projects', 'paper_type')
    op.drop_column('projects', 'class_subject')
    # ### end Alembic commands ###
